fedora-infra/bodhi

bodhi/__init__.py
This uses fedora-infra/pyramid_fas_openid#3.
=> Construct list of groups for pyramid_fas_openid.

bodhi/mail.py, development.ini
I'm not porting this to `pyramid_mailer` because we want this API to work from the Pyramid WSGI frontend as well as the Twisted-based masher.
=> mail: Port from turbomail to smtplib

bodhi/models/models.py, bodhi/services/updates.py, bodhi/static/css/site.css, bodhi/static/js/update_form.js, bodhi/templates/new_update.html, bodhi/templates/update.html, bodhi/util.py, bodhi/views/generic.py
This includes allowing the editing of updates in 2f93ff9, which is essential.
This also adds "revoke" as a possible action on a request which got dropped in
the port from bodhi1 on accident (added back in in e5c248a).
=> Add action buttons to the update view page.

bodhi/validators.py
The bulk of the change is in 7e6e25c.  I ran into a weird case when trying to
test the buildroot override fedmsgs where some updates would have their
``Build`` already in the db, but it didn't have a ``Release`` associated with
it.  The validator here would just vomit in that situation.
This adds logic that checks if the release isn't associated and tacks it on if
its not already there.
=> Add release to build if one is not already associated.

bodhi/__init__.py, bodhi/masher.py, bodhi/models/models.py, bodhi/notifications.py, bodhi/static/js/newsfeed.js, bodhi/tests/functional/test_updates.py, bodhi/tests/test_masher.py, bootstrap.py, development.ini, fedmsg.d/bodhi.py
I went through and tried to trigger each kind of message to make sure that
fedmsg.meta could handle the ones from bodhi2 correctly.  That receiving side
of this is in fedora-infra/fedmsg_meta_fedora_infrastructure#195.
Notably, in 6bc9017 I changed the ``Comment`` json to be backwards compatible
since some things (badges iirc) are looking for certain things there.
Some other things are unrelated but I was too lazy to break them out into their
own pull requests, like:  de9c092 and 8a098e0 and 7aa7c3e and 14cd78f -- sorry
for that.  Long day.
=> Random work with respect to fedmsg messages

README.rst, bodhi/tests/test_metadata.py, bodhi/util.py, bootstrap.py
This ports the code that uses the `yum.update_md` for updateinfo.xml parsing to createrepo_c. It also updates the `bodhi.util.mkmetadatadir` helper for our unit tests as well.
=> Port to createrepo_c

bodhi/models/models.py
With refence to https://github.com/fedora-infra/fedmsg_meta_fedora_infrastructure/issues/96
@ralphbean , wasn't sure if you wanted to publish to fedmsg for that single template or all the templates. Currently it publishes to fedmsg for that particular template.
=> Adding long bodhi template to fedmsg

bodhi/masher.py
fixes #139 
This happens when we run the test suite during the build process on koji.
=> masher: Gracefully handle exceptions when determing the fedmsg agent

bodhi/templates/master.html
Just like in fedora-infra/datagrepper#166, firefox was *okay* with the
CSP we defined before, but chromium didn't like it.  This makes them
both happy by being more explicit.
=> Be more explicit with Content-Security-Policy

bodhi/metadata.py, bodhi/models/models.py, bodhi/services/updates.py, bodhi/tests/functional/test_stacks.py, bodhi/tests/functional/test_updates.py, bodhi/tests/models/test_models.py, bodhi/tests/test_masher.py, bodhi/tests/test_metadata.py
As opposed to when it's initially pushed to testing, which is how it is currently done.
=> Generate the update ID/alias upon creation

bodhi/model.py
We hit this recently in production after a postgres upgrade and only fixed it
in the Update notes. Fixes issue #147 
https://fedorahosted.org/bodhi/ticket/767
=> model: Hack around extraneous \n characters in the comment text (issue #147)

bodhi/model.py, bodhi/tests/test_model.py
This fixes a number of issues that have popped up recently.
https://fedorahosted.org/bodhi/ticket/782
https://fedorahosted.org/bodhi/ticket/783
https://fedorahosted.org/bodhi/ticket/784
=> Use the kitchen unicode/byte converters to mitigate encoding nightmares

bodhi/models/models.py, development.ini, production.ini
This should fix the https://fedorahosted.org/bodhi/ticket/670 for bodhi2 (develop)
=> Fix bodhi trac ticket #670 (bodhi2)

bodhi/schemas.py, bodhi/services/updates.py
The bodhi2 API is close to compatible with bodhi1 in many ways.  One
place that changed is that where previously ``?release=F19`` was used to
specify that you wanted updates only for F19, now we use
``?releases=F19``.  This patch adds some backwards compatibility so that
the old RSS feeds should work.
=> Support bodhi1 RSS feeds as best we can.

bodhi/models/models.py, bodhi/tests/functional/test_updates.py
Things like blockerbugs rely on this, so we might as well remain compatible for now.
=> compat: Return the 'updateid' as well as the 'alias'

bodhi/security.py, bodhi/services/builds.py, bodhi/services/comments.py, bodhi/services/csrf.py, bodhi/services/overrides.py, bodhi/services/releases.py, bodhi/services/stacks.py, bodhi/services/updates.py, bodhi/services/user.py, development.ini, production.ini, staging.ini
This was the root cause of why the typeahead.js search box stopped
working.  Apparently, in the last year browsers got much more strict
about enforcing CORS and ajax requests from typeahead to the server were
failing that policy.
I implemented a proxy class to relay pyramid configuration to cornice.
The docstring of that class details why it is as complicated as it is.
=> Declare CORS allowed-origins for cornice.

bodhi/tests/functional/test_updates.py, bodhi/validators.py
This doesn't fix any bugs, per se.  It's an improvement from a UX perspective.
I realized when working on the bodhi1->bodhi2 redirects that bodhi1 has
a behavior that I use all the time where you can visit
https://admin.fedoraproject.org/updates/nethack and be shown updates of
that package.  In bodhi2, this just gives you a 404, because there's no
update named just "nethack" -- it's a package.
This patch enhances the update_id validator to raise a 302 redirect
*if* the update_id isn't an update id but it *is* a package name.
We could take this or leave it.  It would be nice from a UX point of view, but
maybe confusing to someone if they're trying to use the API and then get a 302
redirect.  On the other hand, I find it hard to imagine somewhere where someone
is programmatically providing …
=> Redirect to a package's updates if it exists.

bodhi/__init__.py, bodhi/services/markdown.py, bodhi/templates/master.html, bodhi/views/generic.py, development.ini, production.ini, staging.ini
Also, move our markdown endpoint to a cornice service so that it gets all the
nice CORS stuff from yesterday.
=> Make our CORS Content-Security-Policy configurable.

bodhi/renderers.py
Apparently, ``tostring(...)`` is deprecated and this is the way you're
supposed to do this.  It worked in our virtualenvs, but was failing in
staging with the version of PIL in place there.
I was getting this traceback in staging:
```python
mod_wsgi (pid=21696): Exception occurred processing WSGI script '/usr/share/bodhi/bodhi.wsgi'.
Traceback (most recent call last):
File "/usr/lib/python2.7/site-packages/paste/deploy/config.py", line 291, in __call__
return self.app(environ, start_response)
File "/usr/lib/python2.7/site-packages/pyramid/router.py", line 242, in __call__
response = self.invoke_subrequest(request, use_tweens=True)
File "/usr/lib/python2.7/site-packages/pyramid/router.py", line 217, in invoke_subrequest
response = handle_request(request)
File …
```
=> Get captcha working in staging again.

bodhi/templates/update.html, bodhi/util.py
As discussed in #167.
- Don't show ABORTED taskotron results in the update UI.
- Hide ABORTED taskotron results from server-side checks.
=> Don't deal with ABORTED taskotron checks.

bodhi/templates/pkg.kid
- Community link dropped, it just redirects to a package search page
- PkgDb link fixed
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/fedora-infra/bodhi/171)
=> Update package links

bodhi/templates/master.html, development.ini, production.ini, staging.ini
We're disabling stacks for the initial release because, while you can create
stacks, you can't automatically create updates *from* a stack (which was the
whole point).  We'll work on that for a later release.
=> Disable stacks for the initial release.

bodhi/push.py
The cert we're going to be using is just called "shell", so we might as well
make that the default to save on typing for releng.
=> Change default cert_prefix for push tool.

bodhi/models/models.py, bodhi/tests/functional/test_updates.py
This will make fedmsg.meta compatibility between bodhi1 and bodhi2 updates
*much* more simple.
=> Add the 'submitter' field back to Update JSON.

bodhi/services/builds.py, bodhi/services/updates.py, bodhi/tests/functional/test_updates.py, bodhi/validators.py
This check is currently broken, in that it won't let you submit a build of
foo-1.2.3 for F22 if you already submitted foo-1.2.3 for F23(!)  That's
crucial functionality we need in place.
This kind of validator is something that got ported over from bodhi1 which
had years of policy baked on to it.  Now that taskotron is doing depcheck
runs and bodhi2 is using the results of those runs to gate in the mash
process... we don't even need this validator anymore, do we?
=> Stop validating rpm versions.

bodhi/models/models.py
I think some people are hitting this when they comment
on an update that kicks it over the karma threshold, but
that threshold checking raises an exception.  It blocks the
comment from going through all together because the exception
bubbles all the way up to cornice.
This should make it so that the comment can still go through
if karma threshhold checking fails, but it will still log the
exception so we can dig more into them later.
=> Catch other bodhi exceptions when commenting.

bodhi/services/builds.py, bodhi/services/updates.py
Otherwise, you get the traceback you got in #239.  (This fixes #239.)
validate_build_tags is the one that builds ``request.buildinfo['tags']``.
=> validate_build_tags must come before validate_acls.

bodhi/services/builds.py, bodhi/services/comments.py, bodhi/services/overrides.py, bodhi/services/releases.py, bodhi/services/stacks.py, bodhi/services/updates.py, bodhi/services/user.py
This is used to used to disambiguate columns from multiple tables.
Fixes #179.
=> Suppress SAWarnings by using labels.

bodhi/models/models.py, bodhi/templates/fragments.html, bodhi/templates/update.html, bodhi/tests/models/test_models.py, bodhi/tests/test_masher.py
But only on the user profile page and the comment list page.
It doesn't make sense to show the name of the update if you're looking
**at** the page for **that** update already... so suppress it there.
Fixes #215.
=> Display the update in the comment fragment.

bodhi/tests/functional/test_updates.py, bodhi/validators.py
The root cause was that we have this ``validate_acls`` validator which is
used in two different ways but it was only programmed to handle one of
those two. It became critical when that first manner would fail silently if
it was called in the second manner.
I've fleshed out that validator to now handle its two different code paths
and left lots of comments about my findings.  We should get this out asap..
Longer term, we should break the validator into two different ones that
handle each role accordingly (for updates and lists of builds).
Fixes #282.
=> Fix the ACLs issue for set_request and edit.

bodhi/models/models.py, bodhi/services/updates.py, bodhi/static/js/update_form.js, bodhi/tests/functional/test_updates.py, bodhi/validators.py
*Really*, when submitting an update with builds that are in multiple
releases, detect that in the cornice service, split the builds up, and
create multiple updates, one for each release.
This involved moving some logic out of ``Update.new`` and into the cornice
service, so that the cornice service could detect the scenario and call
``Update.new`` multiple times as necessary.
I also took the opportunity to expand the new "caveats" API that
karma/comments has to return some additional information from the updates
service.  Those caveats get rendered as pop-ups after a successful update
submission before you get redirected to a new page.
When submitting a single update, you get redirected to the view page for
that update afterwards.
When submitting multiple updates, you get redirected to the …
=> Support multi-release updates.

bodhi/static/css/site.css, bodhi/templates/home.html, bodhi/templates/master.html
This ends up making the navbar much more crowded than it used to be, so we now
have to add a crazy css media query to get the navbar to collapse into "mobile"
mode much sooner (larger) than it normally would.
* Fixes #231.
* Partly addresses #201.
=> Move the search bar from the frontpage to the header.

bodhi/static/js/update_form.js
This fixes #260 by actually removing typo'd items from the list when creating
new updates.
=> Remove builds and bugs when unchecked.

bodhi/services/updates.py
This is the last pull-request of many that will fix #258.  The others involved
standardizing the error reporting popups and suppressing some errant redirects.
=> Surface set_request errors to the user.

bodhi/static/js/update_form.js
This fixes a bug introduced in #304.
When you do multi-release updates, the JSON response that comes back contains
all the created updates in a list.
* Fixes #352.
* Fixes #329.
=> Bugfix when redirecting after multi-release update creation.

bodhi/static/js/cabbage.js, bodhi/static/js/forms.js
Currently after pressing the button to make an update go to testing/stable
the bodhi logo (the cabbage) starts spinning.
This is really nice but easy to miss.
With this change the mouse cursor will also change, making it clearer that
something is going on.
Fixes https://github.com/fedora-infra/bodhi/issues/355
=> Change the mouse cursor when doing an action

bodhi/cli.py
---
Reimplementation of https://fedorahosted.org/bodhi/ticket/773. I assume the docs are generated from `click` automatically now?
=> bodhi: add --notes-file argument

bodhi/masher.py
* Primarily, this using ``update.abs_url()`` to get an absolute url for the
updates in a consistent way (instead of constructing our own absolute urls in
the masher).
* Secondly, it tacks ``update.title`` on the end of the line for
human-readability (to understand what the list of URLs is about).
Fixes #207.
=> Fix update-testing report links.

bodhi/masher.py, bodhi/models/models.py
* Fixes #369.
* Fixes #320.
Also, ``MasherThread.check_karma_thresholds`` can be confusing when compared
with ``Update.check_karma_thresholds``, so I renamed it just to differentiate
them for human readers.
=> Assign autokarma credit to 'bodhi' not the comment author.

bodhi/templates/override.html
Super simple.  #374 complains correctly that the calendar icon doesn't do
anything.  The datepicker lib we're using doesn't easily extend to allow being
triggered by a button, so let's just remove the icon so we can move on to
hacking on other bugs/features.
Fixes #374.
=> Remove calendar icon.

bodhi/models/models.py, bodhi/templates/update.html
* Fixes #362.
This should cut down on any depcheck false positives we report/use and could
also maybe make our query-load lighter on resultsdb.
=> Be more specific with time in our taskotron queries.

bodhi/static/js/forms.js, bodhi/templates/new_update.html
This fixes #397.
The bug was introduced in 2c3bba9e when we were trying to fix something else.
The bug stems from the way the list of submitted builds gets generated in
javascript before it is POSTed to the server.  It looks like this when you have
one checkbox unchecked:
```javascript
[
"foo-1.2.3-1.fc23",
"bar-0.1.0-1.fc23",
false,
"baz-900-2.fc23",
]
```
The code in this patch only pushes that ``false`` value into the list **if**
the checkbox is specially marked with a ``data-singleton`` HTML5 attribute
(which I made up).  So, now:
- lists of checkboxes should *not* get the ``false`` value
pushed (fixing #397).
- singleton checkboxes will still get their ``false`` value
included (keeping #348 in good shape).
=> Differentiate singleton and sequence checkboxes(lists).

bodhi/__init__.py, bodhi/models/models.py, bodhi/templates/fragments.html, bodhi/templates/master.html, bodhi/templates/release.html, bodhi/templates/tables.html, bodhi/tests/models/test_models.py
Provide the data in the template for this by hanging another lazily
evaluated
'reified' property to the request that returns the same data that the
``bodhi.services.releases`` cornice service does.
* Fixes #350.
=> Add a "Releases" dropdown to the toplevel navbar.

bodhi/models/models.py, bodhi/services/overrides.py, bodhi/static/js/override_form.js, bodhi/tests/functional/test_overrides.py, bodhi/validators.py
Under the hood, it creates separate overrides for each NVR
and the JS web client redirects you appropriately.
Added two new tests to cover these cases.  All previous tests cases still pass.
Fixes #415.
=> Allow submitting multiple NVRs for an override.

bodhi/static/js/override_form.js, bodhi/views/generic.py
This then gets used by the new buildroot override form to search for builds
that either either updates candidates **or** in the testing tags or the pending
testing tags.
* Fixes #327.
=> Expand latest_candidates to accept testing=true/false.

bodhi/util.py
We don't use anything fancy to clear the spinner.  People just have to reload
the page.  BUT, it's a quick and easy replacement for the ugly ``None`` we had
on the page before..
=> Show a spinner while we have no bug titles.

bodhi/mail.py
We get it *all the time* in the mash for trying to send email to users that
don't have a FASUSERNAME@fedoraproject.org email address.
That's a problem -- we want them to get mail, so we should get their preferred
email from FAS or FMN and use that.
In the meantime, let's just complain about it with a **warning** in the logs so
that we (the bodhi admins) don't get a ton of spam system email about it.  It
makes it hard to sift through the emails for more important problems.
=> Demote this log statement.

bodhi/services/updates.py, staging.ini
This is mostly debugging I used to figure out what was wrong with #435.
The real fix for that is deployed in [this ansible commit](https://infrastructure.fedoraproject.org/cgit/ansible.git/commit/?id=56856cf89cb2f6e242543ad382ffdcf8add2ed82).
=> Set epel test requirement message.

bodhi/static/js/forms.js
fixes #434 (tested in staging)
=> js: Fix the data-singleton conditional to get checkboxes working again

bodhi/templates/update.html
This adds a little alert panel on the update view for critical path updates.
It would show up just below the Locked panel and the Push/Edit buttons, but
above the Update Notes.
Fixes #339.
=> Indicate that an update is a critpath update.

bodhi/views/generic.py
Recently adding the extra calls to look for testing and pending testing builds
too created the possibility of duplicates here.
Fixes #450.
=> Prune duplicates from /latest_candidates

bodhi/static/css/site.css, bodhi/templates/fragments.html, bodhi/templates/new_stack.html, bodhi/templates/new_update.html, bodhi/templates/override.html, bodhi/templates/update.html
=> Add a markdown cheat sheet modal.

bodhi/static/js/update_form.js
- in the new update form which fixes #391.
- also disallow empty checkboxes which fixes #347.
=> Support "tab" as a select trigger

bodhi/consumers/masher.py
Potentially fixes #418.  See that issue for more details.
Before accepting this, we need to think if changing the set of updates being
mashed at this point in the mash would be otherwise problematic.  It just seems
like a waste to kill the whole mash if one update has oddball tags at this
point in the process.
If we *don't* want to accept this, we might want to consider cherry-picking
f168b46 and bba5123, which are probably nice on their own.
=> Eject from mash instead of failing when tag actions fail.

bodhi/services/builds.py, bodhi/services/comments.py, bodhi/services/csrf.py, bodhi/services/errors.py, bodhi/services/markdown.py, bodhi/services/overrides.py, bodhi/services/packages.py, bodhi/services/releases.py, bodhi/services/stacks.py, bodhi/services/updates.py, bodhi/services/user.py, bodhi/static/css/site.css, bodhi/templates/errors.html, bodhi/templates/master.html, bodhi/views/generic.py
A lot is going on in this one.
- Add cornice error handlers to all of our services.
- A new template is added to show generic errors.
- An HTML error handler is added for cornice views.
- A general exception catcher is installed at the pyramid level, that passes
errors to the cornice handler for rendering.
- The master template is updated to handle the new special case where there is
no `matched_route` (a 404 page).
Fixes #432.
=> Add a generic error template and handling.

bodhi/static/css/site.css
=> Fix overflow in markdown comment areas.

README.rst
This uses the bodhi2 dump instead of relying on a bodhi1 dump that then
had to be converted for bodhi2.
Fixes https://github.com/fedora-infra/bodhi/issues/466
=> Adjust the README to document using the latest DB dump

bodhi/bugs.py
With this commit we won't make the comment but instead we raise an
exception and log it if a comment has more than 65535 characters.
Fixes https://github.com/fedora-infra/bodhi/issues/330
=> Check the size of the comment before sending it to bugzilla

bodhi/__init__.py, bodhi/events.py, bodhi/notifications.py
We had been calling this a "transaction manager" but after reading [the docs](https://zodb.readthedocs.org/en/latest/transactions.html#the-pickledatamanager) I see that the transaction module provides the transaction manager and we provide specialized "data managers" on our side.
This adds a data manager for Fedmsg.
I ended up having to make this ``ManagerMapping`` object that maintains state about which data manager **instance** is associated with which transaction manager instance.  I started trying to implement it in ``notifications.publish(...)`` but found that the logic grew very quickly and felt like I had to abstract it out.
Fixes #458.
We should probably split this out into fedmsg itself some day and just have bodhi.notifications use the data manager that it provides.  Other …
=> A fedmsg data manager

bodhi/__init__.py, bodhi/models/models.py, bodhi/services/overrides.py, bodhi/services/stacks.py, bodhi/templates/master.html, bodhi/templates/user.html, bodhi/tests/functional/test_overrides.py, bodhi/validators.py
This changeset turns ``request.user`` into a munch object where it used to be a sqlalchemy ``User`` object, mediating the *complex failure scenario* detailed in #473.
It was a little more involved than I thought it would be, but not too bad.  All the tests pass (and I didn't have to modify any of them).
=> Munch it up!

bodhi/util.py
This should make sure we do no have unbarrable links anywhere but that
we are using the title instead.
Fixes https://github.com/fedora-infra/bodhi/issues/221
=> Make the link to updates display the title but rely on the alias

bodhi/models/models.py, bodhi/tests/models/test_models.py
... as opposed to removing all tags.
This will hopefully work around the following issue we just hit in production:
```
2015-09-06 00:12:05,405 INFO  [bodhi][MainThread] Removing f23-updates-candidate tag from grub2-2.02-0.23.fc23
2015-09-06 00:12:05,526 ERROR [bodhi][MainThread] Failed to create update
Traceback (most recent call last):
File "/usr/lib/python2.7/site-packages/bodhi/services/updates.py", line 347, in new_update
result, _caveats = Update.edit(request, data)
File "/usr/lib/python2.7/site-packages/bodhi/models/models.py", line 750, in edit
b.untag(koji=request.koji)
File "/usr/lib/python2.7/site-packages/bodhi/models/models.py", line 555, in untag
koji.untagBuild(tag, self.nvr)
File "/usr/lib/python2.7/site-packages/koji/__init__.py", line 1556, in __call__
return …
```
=> Unpush builds when they are removed from an update

bodhi/consumers/masher.py, bodhi/notifications.py, bodhi/push.py
And use that option in the masher so messages don't get queued up until we're all done.
=> Add an option to bypass the fedmsg transaction/data manager.

bodhi/models/models.py
This will add it back to the ``request.user`` object (now a munch object), which will fix #514.
=> Add "groups" to the User JSON repr.

bodhi/notifications.py
If fedmsg doesn't have an endpoint, then we will fail in a Very Ugly Way in
``tpc_finish()``.  We should do this check here in ``tpc_vote()`` so that we
can fail early before things get into a weird, inconsistent state.
=> Ensure that fedmsg can publish before voting.

bodhi/bugs.py, bodhi/models/models.py, bodhi/tests/test_masher.py
It used to be that we would take the version of the first build in a
multi-build update and use it everywhere for the "fixed in version" field.
This should more correctly map builds to bugs.
Fixes #513.
=> Correctly map builds to bugs when closing.

bodhi/models/models.py, bodhi/tests/functional/test_updates.py
This is for my personal use.
It would be cool if Update JSON included a True/False of whether or not updates
are ready to be pushed to stable or not.  I would use this from local scripts
to figure out what updates I need to go push to stable.  Historically, I would
scrape the comment history looking for bodhi to tell me its good to go.
=> Include meets_testing_requirements in Update JSON.

bodhi/bugs.py, bodhi/models/models.py, bodhi/tests/test_masher.py
This should fix #428.
Furthermore, I try here to stick with how the anaconda team uses the fixedin
field by hand so that we don't disrupt their workflow.  See this bug for an
example:  https://bugzilla.redhat.com/show_bug.cgi?id=1256072
=> Make the fixedin field additive.

bodhi/models/models.py, bodhi/templates/update.html
So that they are in the same order as in the comment form at the bottom of the page.
Fixes #498.
=> Flip the order of the feedback items.

bodhi/metadata.py
https://bugzilla.redhat.com/show_bug.cgi?id=1256336
=> metadata: Use GZ compression for the updateinfo on RHEL5 (fixes #534)

README.rst
Improved [README.rst](https://github.com/fedora-infra/bodhi/blob/develop/README.rst) by adding the links. Presently the user would have to search for them especially [sqlalchemy.url](https://github.com/fedora-infra/bodhi/blob/02d0a883c156d9a27a4dbac994409ecf726d00a9/development.ini#L413)
=> Added link to developement.ini and sqlalchemy.url

bodhi/tests/functional/test_comments.py, bodhi/tests/functional/test_updates.py
- Ensure you can comment on a locked update.
- Ensure that the comment won't trigger threshold action if your comment
takes
things over or under the stable/unstable karma thresholds.
Relates to #539.
=> Add tests for commenting on locked updates.

bodhi/models/models.py
We did this just a few lines above for all of the package maintainers, but we
forgot to do it here for all the people who commented on the bug.  This should
cut down on superfluous warnings in our logs *and* get more email to people who
should be getting it.
=> Use email over username here (if we have it).

bodhi/security.py, bodhi/services/updates.py, bodhi/tests/functional/test_updates.py, bodhi/validators.py
* Fixes #190
* Fixes #321
This didn't go the way I expected.  I expected to make the ``bodhi.security.package_maintainers_only_acl`` acl smarter by moving some of the logic over from ``validate_acls``, and then rewriting  ``validate_acls`` to use that pyramid acl.  This turned out to not be the best idea.
First, pyramid acls must return a list of principals indicating who is and who isn't allowed to access a resource.  For us, that would mean returning a list of *all* proven packagers and *all* people with commit access (by querying pkgdb) every time we load a page.  `validate_acls` is smarter than this in that it first checks for provenpackager status and then skips querying pkgdb if the person is in that group.  I thought about trying to be clever by returning a *generator* from our acl …
=> Use validate_acls to produce the can_edit value.

bodhi/models/models.py
This removes a *ton* of stuff that isn't needed.
Right now we return something like this:
```javascript
{
update: {
user: {
groups: [{
name: "packagers",
users: [
id1,
id2,
id3,
id4,
...
],
}],
}
}
}
```
Previously, we would notice that we have already ``seen`` the ``User`` model in
the json recursion, and turn that list of users into just a list of IDs... but
this is still way too much data.  If you are getting a *list of updates*, you
get the owner of every update, and every group their in, and the id of every
user in every one of those groups *over and over* for every update in the list
you retrieved.
With this code change, we detect that we have already ``seen`` the ``User``
model before diving into the ``_expand(..)`` recursion, and we just drop that
innermost user list all together. …
=> Cut down on recursive data in the JSON api.

bodhi/consumers/masher.py
With an extra change to our ansible logging configuration in ``/etc/fedmsg.d/``, this will fix #555.
=> Set thread name for masher logging.

bodhi/ffmarkdown.py, bodhi/templates/fragments.html, bodhi/tests/functional/test_generic.py
This allows writing things like `python#12345` and get it markdownified into a link to bug 12345 in the upstream Python bug tracker.
=> Markdown bugurls

bodhi/cli.py
Otherwise, it prints that header out every time.
=> Suppress "Caveats:" text if there are no caveats.

bodhi/metadata.py
There's no need to get two errors emails here.
Are these even actionable?  Should we further demote this to a warning?
Does it indicate a serious underlying bug that needs to be fixed?
If it's not serious, let's demote it to a warning.  Otherwise, it will
contribute to error-fatigue.  We'll stop paying attention... ;)
=> Collapse these two emails into one.

bodhi/cli.py, bodhi/metadata.py
This turned out a bit more finicky than I expected, but it does
work. Allows downloading updates by CVE, update ID, and/or build
NVR, accepting comma-separated lists for each. You can use
any combination of the three to download multiple updates at
once.
I couldn't find a better way to do 'one of these three
things must be specified' in click, please let me know if there
is one.
The old CLI added i386 and i586 --arch options for i686 systems,
but that was done back in 2009 referencing an i586 update for
F11; I'm pretty sure we don't have any i386 or i586 builds any
more.
We could add an option to set the arches to download, I guess,
but it makes the code a bit finickier and the old CLI didn't
have it, so I left it out for now.
=> CLI: implent update downloading

bodhi/models/models.py, bodhi/tests/__init__.py, bodhi/tests/functional/test_updates.py, bodhi/tests/models/test_models.py, bodhi/tests/test_masher.py
Fixes #567.
Before this change, they were ``<PREFIX>-<YEAR>-<INTEGER>``, where the last
part grows monotonically with each new update.
This commit changes that to ``<PREFIX>-<YEAR>-<HASH>``, where hash is the first
10 characters of a hash of a random uuid.
The problem with the way things are now is that:
- we have a race condition.  If you try to submit two updates at the same time
(via a script, this is easy to do), then they both go into the code where
their alias is assigned at the same time, they both get the same integer, and
then when they try to commit their database transactions, one wins and the
other fails.
- the alias-assigning code is one of the slower parts of the new update
process.  It takes 1-2s iirc (because it has to query for the latest update
before it and figure out …
=> Restructure the way we assign aliases.

bodhi/__init__.py, bodhi/notifications.py
we're getting tracebacks in production from the mod_wsgi sub-interpreters.
- we used to manually initialize fedmsg on the main thread in ``main()``.
- the child threads however would just secretly re-initialize themselves under
the hood when .publish was called.  this worked fine for a long time and we
had no idea.
- it only became a problem when we added code that checked to see if we were
explicitly initialized before we published.  then the child threads all
crashed at this point.
- this now *explicitly* initializes all threads whenever they call publish for
the first time.
- it also removes the red herring initialization from ``main()``.
=> initialize fedmsg off of the main thread.

bodhi/__init__.py, bodhi/consumers/masher.py, bodhi/consumers/updates.py, bodhi/models/models.py, bodhi/services/comments.py, bodhi/services/updates.py, bodhi/tests/__init__.py, bodhi/tests/functional/base.py, bodhi/tests/functional/test_builds.py, bodhi/tests/functional/test_comments.py, bodhi/tests/functional/test_generic.py, bodhi/tests/functional/test_overrides.py, bodhi/tests/functional/test_packages.py, bodhi/tests/functional/test_releases.py, bodhi/tests/functional/test_stacks.py, bodhi/tests/functional/test_updates.py, bodhi/tests/functional/test_users.py, bodhi/tests/models/__init__.py, bodhi/tests/models/test_models.py, bodhi/tests/test_masher.py, bodhi/tests/test_metadata.py, bodhi/tests/test_utils.py, bodhi/util.py, bodhi/validators.py, bodhi/views/generic.py, tools/metrics.py, tools/pickledb.py
.. in a quest to kill the memory leak.
One thing we get out of this is the ability to explicitly close the sessions that we open.
For some context:
- We used to use global dbsessions for everything.  This is a habit we learned from TurboGears back in the day and it turns out to be a bad one.  With the rewrite to Bodhi2, we ported *most all* instances of that to instead rely on a request-local db session which is nicely scoped, more testable, etc.  This 27-file change ports over the *last* of those old global session references and it removes the global session all together.  Starting this I thought it would be easy since there were only a few instances, but it turned out to be more involved.  These last spots were some of the more tangled places in the code.
The test suite is all passing …
=> Port everything to a request-local db session.

tools/perf-test.py
The output looks kind of like this:
```bash
❯ python tools/perf-test.py e6190c6 7f5e89a 65f319c
Checking ['e6190c6', '7f5e89a', '65f319c']
Is that okay? y
Running on e6190c6
Crunching frontpage http://0.0.0.0:6543/
Crunching update_list http://0.0.0.0:6543/updates/
Crunching update_list_gnome http://0.0.0.0:6543/updates/?packages=gnome-2048
Crunching update_view http://0.0.0.0:6543/updates/FEDORA-2015-13946
Crunching update_view_gnome http://0.0.0.0:6543/updates/FEDORA-2015-16555
Crunching release_list http://0.0.0.0:6543/releases/
Crunching release_view http://0.0.0.0:6543/releases/f22
Crunching comment_list http://0.0.0.0:6543/comments/
Crunching comment_view http://0.0.0.0:6543/comments/2
Crunching user_list http://0.0.0.0:6543/users/
Crunching user_view …
```
=> Improve the perftest tool to compare different commits.

bodhi/consumers/masher.py, development.ini, production.ini, staging.ini
git:// is insecure, therefore do not use it.
Plase also remove the old comps repo on the systems bodhi runs since bodhi will not update the comps URL afaics.
=> Use https for comps Repo

bodhi/consumers/masher.py
This should help to make the reason for cases like #666 more self-evident in the future.
=> Clarify ejection reason.

bodhi/templates/override.html, bodhi/templates/update.html, bodhi/views/generic.py
- If an override exists for each build, add a link to go and edit each one.
- If an override does not exist, add a link to go and create each one.
- If you cannot edit the update, do not show those links.
Fixes #661.
=> Add convenience links from the update page to override management.

bodhi/templates/update.html
This fixes #665 which got introduced in b7690dcc496d60c4b4bb8f30c321fb9d6e010abb.
Things are automatically left-aligned.  No need to introduce some floatery.  It makes things weird at various sizes.
=> Remove extra unnecessary float class from the build list.

bodhi/validators.py
=> Provide a more useful message when the csrf check fails.

bodhi/static/css/site.css
This fixes an issue with the way code-blocks are rendered while maintaining the
behavior we want introduced in #464.
I noticed it while trying to reproduce #671.
=> Explicitly namespace the white-space css rule.

bodhi/static/js/override_form.js, bodhi/static/js/stack_form.js, bodhi/static/js/update_form.js, bodhi/templates/new_stack.html, bodhi/templates/new_update.html, bodhi/templates/override.html
Fixes #627, by not waiting for ``$(document).ready(...);``.
=> Hide the js warning as early as possible.

MANIFEST.in
Fixes #640.
Those files are present in our git repo, but not in the tarball that gets
rolled up into an rpm.  This should get them shipped out to our prod servers on
the next release.
=> Include other font types from fontawesome in our dist.

bodhi/__init__.py
What's weird is that we have *two* other error catchers.  In total:
- We have a *per-service* cornice error handler, defined in ``bodhi/services/errors.py``.
- We have a *pyramid-wide* handler in `bodhi/views/generic.py`.
- Lastly, this *cornice-wide* error handler.
In local testing, I can introduce errors that get handled by the first and
second handlers, but not this one.  Oddly, it seems we're hitting it in
production all the time with that ``None`` error mentioned in #624.
So, I'm not sure what's going on, but hopefully this patch will help us figure
out what's happening, fixing #624.
=> Log a little more information about unhandled errors.

alembic/versions/6383ec38980_add_a_show_popups_attribute_for_users.py, bodhi/__init__.py, bodhi/models/models.py, bodhi/templates/master.html, bodhi/views/generic.py
Fixes #660.
People will still get popups about actions they're undertaking (like,
commenting on an update or error messages when they submit an incomplete form).
=> Allow users to disable global popups.

bodhi/schemas.py, bodhi/services/comments.py, bodhi/templates/user.html, bodhi/tests/functional/test_comments.py, bodhi/validators.py
This allows to ignore comments made by the bodhi user to the user's
updates on the user's page.
Fixes https://github.com/fedora-infra/bodhi/issues/652
=> Add the possibility to ignore the comments made by a specific user

bodhi/ffmarkdown.py
Perl change often use RT#123456 (e.g. http://cpansearch.perl.org/src/SULLR/Net-SSLGlue-1.055/Changes) but perhaps "RT" is too generic, reason why I use "perl" here.
=> Add perl# schema for bug links

bodhi/mail.py, bodhi/models/models.py
This pull-request addresses the first two points mentioned by @nirik in 
https://github.com/fedora-infra/bodhi/issues/626
- Emails are all sent using the sender email set in the configuration file
- All emails sent by Bodhi have a X-Bodhi header
=> Couple of fixes regarding sending emails.

bodhi/models/models.py, bodhi/tests/functional/test_updates.py
=> Don't delete Build objects if they have a corresponding BuildrootOverride

bodhi/schemas.py, bodhi/services/updates.py, bodhi/tests/functional/test_updates.py
Bodhi 1 accepted 'start_date' and 'end_date' query params
(BodhiClient didn't actually allow you to submit them, but
they worked on the server end and we have a QA script that
subclassed BodhiClient and fixed the query method to pass
those parameters). 'start_date' worked like 'pushed_since'
in Bodhi 2, but there is no Bodhi 2 equivalent of 'end_date'.
This commit adds pushed_before, and also the _before
equivalent for all the other _since params (approved_since,
modified_since, and submitted_since). If it's approved I'll
send a follow-up which adds them to the client.
=> query: add _before params matching the _since params

bodhi/consumers/masher.py
This fixes a bug where the current masher summary looks like:
```
PoolThread-twisted.internet.reactor-1 <generator object results at 0x7ff99a30d9b0>
```
=> masher: Iterate over the status results generator

bodhi/metadata.py, bodhi/models/models.py
If a testing update gets a request for stable, currently it will nullify the
`pushed` and `date_pushed` fields. I don't see any reason why we shouldn't keep
these intact, especially considering the fact that we now have `date_stable` and
`date_testing` timestamps. Also, with `date_pushed` set to None, the
`<issued/>` tag in the updateinfo.xml will be omitted, which can lead to other
problems (see
issue #718).
=> models: Don't reset the `pushed` and `date_pushed` flags upon request.

bodhi/consumers/masher.py, bodhi/tests/test_masher.py, bodhi/tests/test_utils.py, bodhi/util.py
Performing all of the tagging in a single koji multicall does not guarantee
order, which means the `koji latest-pkg` could potentially be incorrect if two
versions of the same package went out in the same push.
This patch tags all builds for the same package without using koji multicalls.
=> Tag multiple builds for the same package synchronously.

development.ini, production.ini, staging.ini
Fedora Atomic host uses the `atomic` command and not `dnf` - the wiki
page has more information in either case, at the small cost of
indirection.
=> ini: Link to wiki page for how to get updates instead of inline cmd

bodhi/tests/models/test_models.py, bodhi/util.py
Ok, so this fixes a bug that showed up first as #366, was partway fixed, but
then it showed up again as #705.
We were originally casting bug titles to a ``str`` (to ``bytes`` in python3
terminology) which caused (of course) some encoding errors.  We then addressed
this in 06476bf1 by using's kitchen's ``to_bytes`` which still forces things to
bytes, but does so in a graceful way.
The problem is that we're using mako's ``render_unicode(...)`` function at the
end of the day, which looks for things like bytes and has to force them *back*
to unicode before rendering everything out and giving it a final encoding once
done.  It's that re-decoding that caused the issue in #705.  By just keeping
everything as unicode and letting mako deal with it, this fixes #705.  (I
checked, and ``bug.title`` …
=> Remove unnecessary encoding of bug titles.

README.rst
I was getting "bodhi2 database does not exist" while setting up local instance. These changes fix the error.
=> readme modified to avoid error:database does not exist for local instance

bodhi/tests/functional/test_updates.py, bodhi/validators.py
=> validators: Gracefully handle attempts to edit updates that don't exist

bodhi/push.py
We just hit an issue where a second push was queued up containing locked updates from the first. This lead to a bunch of ejection messages.
=> push: Only attempt to push unlocked updates

bodhi/models/models.py, bodhi/tests/functional/test_updates.py
=> Handling Status for revoking request and test for revoke action

bodhi/templates/update.html
Whenever I request an update go to stable, it then reloads the page for the
update.. but the button is still there.  It should be hidden after you click
it.  This should handle that.
=> Hide "Push to Stable" if request is already "stable".

bodhi/models/models.py, bodhi/templates/update.html
=> Modifying days to stable

bodhi/templates/fragments.html, bodhi/templates/update.html
Fixes #802 
Here are the screenshots:
=> Remove microsecond from timestamp

bodhi/models/models.py, bodhi/tests/models/test_models.py
This avoids situations where bodhi steps on the toes of releng when they are
working with side-tags for outside composes.
=> Only touch tags that we know about.
