bodhi/tests/test_masher.py, bodhi/util.py, bootstrap.py
Reference: https://github.com/fedora-infra/bodhi/issues/121
Signed-off-by: Igor Gnatenko <i.gnatenko.brain@gmail.com>
=> starting replace yum with librepo

bodhi/metadata.py, bodhi/util.py, setup.py
except tests. I don't have time to do it
=> Complete porting to librepo

bodhi/mail.py, bodhi/masher.py, bodhi/models/models.py, bodhi/tests/models/test_models.py, bodhi/tests/test_masher.py, development.ini
=> Mail improvements along with the updates-testing digest

bodhi/__init__.py, bodhi/masher.py, bodhi/models/models.py, bodhi/services/updates.py, bodhi/tests/__init__.py, bodhi/tests/functional/test_updates.py, bodhi/tests/models/test_models.py, bodhi/tests/test_masher.py
=> post push karma policy checking

bodhi/tests/functional/test_overrides.py, bodhi/validators.py, development.ini
=> Limit the length allowed for buildroot overrides.

bodhi/templates/master.html, development.ini
For https://fedoraproject.org/wiki/Infrastructure/FY16_frontend
If you leave the fedmenu bits out of the config, it just never shows up.
=> Add fedmenu.

bodhi/models/models.py, bodhi/renderers.py, bodhi/services/comments.py, bodhi/services/overrides.py, bodhi/services/updates.py, bodhi/services/user.py, bodhi/tests/functional/test_comments.py, bodhi/tests/functional/test_overrides.py, bodhi/tests/functional/test_updates.py, bodhi/tests/functional/test_users.py
Also, add RSS for buildroot overrides that we forgot way back when...
=> Make liferea happy.

bodhi/__init__.py, bodhi/templates/master.html, bodhi/util.py, bodhi/views/generic.py, tools/python-fedora-api-test.py
This fixes #159.
Also, remove duplicate pkg_resources code.
We had two implementations of the same function ``version()``.  This
ditches the one we just added in ``bodhi/__init__.py`` in favor of the one
in ``bodhi/util.py``.
=> Add a link to the project and to file bugs to the footer.

bodhi/services/builds.py, bodhi/services/comments.py, bodhi/services/overrides.py, bodhi/services/releases.py, bodhi/services/stacks.py, bodhi/services/updates.py, bodhi/services/user.py
=> Fix the "totals" returned by the pagination logic in our cornice services.

bodhi.spec, bodhi/notifications.py, bodhi/push.py, setup.py
Currently untested in staging.
=> push: Add an initial bodhi-push tool

bodhi/masher.py
The build-branched nightly cron job takes care of the mashing for us, so only
do the other stuff.
=> masher: Don't mash or do any repo-related things to pending releases

bodhi/templates/update.html
This should hopefully resolve issue #233 and part of #220
=> templates: Display the Push to Stable button if we meet the testing requirements

bodhi/util.py
This seems to work in production.
=> buildsys: Fetch the RPM headers based on the src package

bodhi/tests/functional/base.py, bodhi/tests/functional/test_updates.py, bodhi/tests/test_masher.py, bodhi/validators.py, development.ini, tools/perf-test.py
Confirmed via both the test suite *and* local hand testing of the web UI.
=> Check and test for empty builds for edited updates.

bodhi/templates/update.html
=> Remove these hrefs which make location.reload() unstable.

bodhi/static/js/forms.js, bodhi/templates/update.html
=> Don't hide popup errors after 10s.  Keep them around and make them dismissable.

bodhi/services/updates.py, bodhi/templates/fragments.html, bodhi/templates/tables.html, bodhi/templates/updates.html
=> Show the request in tables of updates.

bodhi/models/models.py, bodhi/tests/functional/test_updates.py
=> Include test_case JSON in update output.

bodhi/templates/update.html
The questions for general karma and critical path karma really don't make a lot of sense and are somewhat confusing. I've rewritten them to be more logical in the context of how they are presented on screen.
This should fix #222.
=> Reworded "karma" and "karma_critpath" questions to make more sense.

bodhi/models/models.py
Fixes #226 and pays homage to #314.
=> Post on bugs with update url, not bug url.

bodhi/captcha.py
The main case here is where we handle HTTPGone.  The vast majority of our
production tracebacks are from here where (somehow) people are loading forms
that generate captchas (which works) and then way later, they are requesting
those same captcha images again (over 300 seconds later.. that's like 5
minutes). I *bet* this is happening if someone has a bodhi update page open,
and then their browser crashes and tries to restore its previous state, or
something like that.
Anyways, this patch adds a catch to that main "captcha is expired"
``InvalidToken`` traceback that is spamming our logs.  It turns it into a 410
Gone statuscode, which makes sense. While testing it, I tried passing in
garbage which generated a different ``TypeError`` from the base64 module, so I
caught that too.
Fixes #237.
=> Handle some errors from the captcha generator.

bodhi/mail.py
This is intended to address #377, but I'm not sure if it will fix it or not.
Also made a cosmetic commit to address readability.
=> Try converting the final email body to utf8 before sending.

bodhi/models/models.py
This resolves part of issue #368
=> Don't comment on or modify Security Response bugs for updates in testing

bodhi/security.py
=> Don't add people to empty groups.

bodhi/templates/update.html
=> Link to various places from the list of builds on the update page.

bodhi/services/releases.py, bodhi/templates/release.html
* Fixes #403.
* Helps with #263.
=> Add more stats and links(!) to the release pages.

bodhi/templates/fragments.html
.. in the "comment" fragment.  This should fix #405.
=> Push testcase feedback into its own row

bodhi/util.py
This should in part address #426.
=> Retry and log errors about koji rpm headers.

bodhi/templates/override.html
=> Don't show invalid dates in datepicker.

bodhi/models/models.py
This fixes #411.  Turns out that el6 has no pending tags and that's okay, but
it was breaking us anytime someone tried to edit an el6 update.
I think this works in the other cases where tagging is done through
``Update.add_tag`` and ``Update.remove_tag``, because those use
``koji.tagBuild(...., force=True)``.  The force, I imagine, is hiding whatever
underlying issue this generates.  Anyways, we can only get faster by not
bothering koji with requests to tag stuff into empty tags.
=> Don't try to tag stuff with the u'' tag.

bodhi/models/models.py, bodhi/services/overrides.py, bodhi/static/js/search.js
=> Make buildroot overrides searchable.

bodhi/models/models.py, bodhi/services/updates.py, bodhi/tests/functional/test_updates.py
.. meanwhile try to fix the problems in #424 which in turn fixed #365, but
introduced other problems.
See how this modified the test suite (and what it leaves untouched) to get
a feeling for what it does.
=> Add caveats to update auto-obsoletion and..

bodhi/schemas.py, bodhi/services/packages.py, bodhi/static/css/site.css, bodhi/static/js/search.js, bodhi/tests/functional/test_packages.py
This should improve the search results and help bring #229 to a close.
=> Add a searchable packages service.

bodhi/models/models.py, bodhi/tests/functional/test_comments.py, bodhi/tests/functional/test_updates.py
=> Send testing updates back to a pending state when a new build is added

bodhi/static/js/live.js
=> Cut down on js console errors by correctly checking for this function.

alembic/versions/13cfca635b99_add_update_date_testing_stable_.py, alembic/versions/3dbed75df3fe_set_testing_stable_dates_for_all_old_.py, bodhi/models/models.py, bodhi/templates/update.html, bodhi/tests/functional/test_updates.py, bodhi/tests/test_masher.py
... instead of scraping the comments.
=> Add Update.date_{testing,stable} db timestamps and refactor Update.days_in_testing

bodhi/consumers/updates.py, bodhi/services/updates.py
:construction: :warning: UNTESTED :skull: :fire:
=> consumers: Query the wiki for test cases on the backend (fixes #314)

bodhi/notifications.py
=> Some fixes to fedmsg transactions.

bodhi/schemas.py, bodhi/templates/update.html
... and even empty text for comments.
Fixes #451.
=> Allow shorter notes for updates and overrides.

alembic/versions/70a58ae9f90_index_update_title.py, bodhi/models/models.py
I haven't done any benchmarking to see if this helps, but I'm guessing it will since I think the Search widget searches over this field.
=> models: Index the Update.title and date_submitted

bodhi/tests/test_masher.py
Also, remove some dead code from the masher tests.
=> Add force=True to our mock checks in the bodhi tests.

bodhi/templates/update.html
=> Added a class to ${build.nvr} element in update template. Closes #508

bodhi/consumers/masher.py, bodhi/models/models.py
This is in-part related to #515.
=> Provide markdown links to obsoleted updates.

bodhi/templates/override.html
fixes https://github.com/fedora-infra/bodhi/issues/485
=> Display the submitter of the override on the override page

bodhi/services/releases.py, bodhi/templates/master.html, bodhi/templates/release.html
Relates to https://github.com/fedora-infra/bodhi/issues/484
=> Link to lists of buildroot overrides

bodhi/validators.py
This should speed things up by avoiding making un-necessary calls to
pkgdb.
Fixes https://github.com/fedora-infra/bodhi/issues/489
=> Check if an user is a provenpackager before checking their ACLs

setup.py
=> Added required dep from fedmsg's setup.py extra_requires. Fixes #506

bodhi/models/models.py, bodhi/tests/functional/test_updates.py
=> Reset karma on updates when the builds change.

bodhi/models/models.py, bodhi/tests/functional/test_updates.py
This enumerates the list of added and removed builds in markdown format, so it should look nice and comprehensible.
=> Make the edit comment look pretty.

bodhi/bugs.py, bodhi/models/models.py, bodhi/tests/test_masher.py
This is the third and hopefully final time.
We got pinged by some Red Hatters who say that there's a precedent for handling
that field in a particular way.  This should hopefully meet that criteria.
Fixes #531.
=> Tweak rhbz fixedin handling (again)

bodhi/models/models.py, bodhi/tests/test_masher.py, development.ini, production.ini, staging.ini
Just like in #359, except here we also conditionalize yum/dnf advice on EPEL/Fedora.
Lastly, also fix newlines in the config, which
- fixes #335
- fixes #357
That will also need to be applied to our ansible production/staging config.
=> Change yum references to dnf

bodhi/bugs.py
See https://fedoraproject.org/wiki/BugZappers/BugStatusWorkFlow
- Fixes #427.
- Fixes #401.
=> Close as ERRATA

bodhi/schemas.py
- Relates to #267.
- Fixes #279.
=> Let people query the API up to 1000 items.

bodhi/static/js/forms.js, bodhi/templates/new_stack.html, bodhi/templates/new_update.html, bodhi/templates/override.html, bodhi/templates/update.html
=> Add more spinning indicators to our many buttons.

bodhi/models/models.py
These get artificially added in, so we need to artificially prune them as well.
Fixes #343.
This cuts the bytes-returned by queries down in half *again*::
❯ http get http://0.0.0.0:6543/updates/ | wc
0   85607 1087158
❯ http get http://0.0.0.0:6543/updates/ | wc
0    4919   58298
=> Short-circuit recursion specifically for test cases.

bodhi/consumers/masher.py
=> masher: Ensure updates cannot be partially tagged before begin ejected

alembic/versions/2defe1107259_set_the_pushed_flag.py, bodhi/models/models.py
=> Fix the 'pushed' column.

bodhi/services/comments.py, bodhi/services/overrides.py, bodhi/services/updates.py, bodhi/services/user.py, bodhi/services/zz_redirects.py, bodhi/tests/functional/test_updates.py
This provides some backward compatibility layer with bodhi1
Fixes https://github.com/fedora-infra/bodhi/issues/488
=> Add a redirect from /updates/alias/title to /updates/alias

bodhi/models/models.py
=> models: Allow revoking of requests from unpushed/obsolete updates

bodhi/scripts/untag_branched.py, setup.py
This will also need to be added as a cron job in ansible.
=> scripts: Add a bodhi-untag-branched script (fixes #576)

bodhi/templates/user.html
This fixes #590 and supersedes #596.
=> Provide links to updates by status from user profile page.

bodhi/models/models.py
For #301.
|                       | 258d414                     | de8e1bd                     |
|-----------------------|-----------------------------|-----------------------------|
| update_list           | 3.1128051281 seconds        | 1.60950088501 seconds       |
| update_list_gnome     | 40.4445779324 seconds       | 7.19923591614 seconds       |
| update_view           | 0.643528938293 seconds      | 0.735200166702 seconds      |
| update_view_gnome     | 106.289006948 seconds       | 4.58303284645 seconds       |
| release_list          | 0.0776150226593 seconds     | 0.0293581485748 seconds     |
| release_view          | 0.0262730121613 seconds     | 0.0229330062866 seconds     |
| comment_list          | 144.048120022 seconds       | 5.7861289978 seconds        |
| comment_view …
=> Switch around some lazy loading settings.

bodhi/models/models.py
A small improvement for #301, like #612.
| test              | 2d612e1 | ec3e8b6 |
|-------------------|---------|---------|
| update_list       | 1.55s   | 1.62s   |
| update_list_gnome | 6.27s   | 2.26s   |
| update_view       | 0.68s   | 0.67s   |
| update_view_gnome | 4.32s   | 1.27s   |
| release_list      | 0.02s   | 0.02s   |
| release_view      | 0.02s   | 0.01s   |
| comment_list      | 4.47s   | 1.96s   |
| comment_view      | 0.05s   | 0.04s   |
| user_list         | 0.18s   | 0.33s   |
| user_view         | 0.11s   | 0.08s   |
=> Further prune down JSON recursion for performance.

bodhi/models/models.py
This should hopefully address some of the memory/CPU/db issues discussed in
issue #301
=> models: Use dynamic lazy loading for User.{comments,updates}

bodhi/__init__.py, bodhi/static/js/masher-status.js, bodhi/templates/masher.html, bodhi/templates/master.html, bodhi/views/generic.py
It's way more simple than the releng dash.  But it may just do the job.
Notice the things that are commented out at the bottom of masher-status.js.  Those can be uncommented if we like, or not.  I thought they were a little spammy, but try it out and see what you think.
=> Initial stab at a masher status page.

bodhi/static/js/search.js
…n packages are being searched
=> Fixing the search issue which was redirecting users to a 404 page when packages are being searched

bodhi/scripts/expire_overrides.py
=> Initialize buildsys before trying to expire overrides.

bodhi/models/models.py, bodhi/tests/functional/test_updates.py
=> Include url to an update in JSON body.

README.rst
Adding some information in README.rst 
Thanks :)
=> Information in README

bodhi/static/js/cabbage.js, bodhi/static/js/search.js
=> Let people get quick search results when they press enter.

bodhi/models/models.py, bodhi/tests/functional/test_updates.py
=> Allow the same people to give karma to an update that has had it's karma reset

bodhi/templates/update.html
This fixes #641.  I tried a couple different ways and this was the best.
=> Show the list of builds in a nested table.

bodhi/consumers/masher.py
This should fix #620.  I wasn't able to test this, so give it two looks over before merging.
=> Add more info to the mash summary logging.

bodhi/static/js/forms.js
Fixes https://github.com/fedora-infra/bodhi/issues/623
=> Specify for which field we are returning a notification

bodhi/templates/master.html
This fix the front page when the user is not logged in
=> Ensure there is an user before we try to access show_popups

bodhi/cli.py
This happens when you use the bodhi2 client to create a multi-release update (which I just tried to do for the first time).
=> client - handle case where "total" not in the response.

bodhi/models/models.py
=> Sorts the list of test cases

bodhi/models/models.py, bodhi/tests/models/test_models.py
=> models: Don't delete Bugs that have BugKarma

bodhi/models/models.py
=> models: Query the wiki for tests with a limit of 500 instead of the default of 10

bodhi/models/models.py
=> email: Send comment notifications to the update submitter

bodhi/bugs.py
Trying to fix https://github.com/fedora-infra/bodhi/issues/529
=> Handling Bugzilla deadlock

bodhi/services/updates.py, bodhi/util.py, bodhi/views/generic.py
=> Sort update severity

bodhi/models/models.py, bodhi/tests/functional/test_updates.py
=> models: Ensure that we don't obsolete updates with a pending stable request

bodhi/consumers/masher.py, bodhi/models/models.py, bodhi/services/updates.py, bodhi/tests/test_masher.py
=> masher: Obsolete older updates after each push (fixes #758)

bodhi/services/updates.py, bodhi/tests/functional/test_updates.py, bodhi/validators.py
=> validators: Disallow older builds from being submitted to testing/stable

bodhi/models/models.py, bodhi/templates/update.html
=> Time to stable

bodhi/templates/fragments.html, bodhi/templates/update.html
=> Display timezone in timestamps

bodhi/tests/functional/test_updates.py, bodhi/validators.py
=> Disallow adding a build from an existing update into another

bodhi/models/models.py, bodhi/tests/functional/test_updates.py
=> Make sure request is None after unpushing
